server:
  port: 8081
  
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/poc
    platform: postgres
    username: postgres
    password: PrajjwalB4@
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: abcd